### ISSUE TITLE
Home app

### ISSUE THREAD

**Issue by zaidmc** [Supereg/homebridge-http-speaker#2]
If I were to use this to control some third party speakers, how are they displayed in the Home app? Can I control volume with Siri (really all I'm looking for)?

**Comment by Supereg** [comment]
The Speaker accessory is not supported by the Home App (and also not by Siri).
Initially I thought it would be introduced in an later version of iOS 11 but now there is still no support in iOS 12 beta.

I think the speaker service in HAP was supposed to be used for AirPlay 2 speakers but those are now discovered via the AirPlay  2 protocol itself. In my opinion the speaker accessory is deprecated and obsolete this we will probably never see support for speaker accessories in the Home App.
But I cannot predict the future 😅

Greets
Andi

**Comment by DanielWeeber** [comment]
The Speaker Service is used for a Video-Doorbell, not as a standalone speaker.

**Comment by Cloudore** [comment]
@DanielWeeber Doorbells were removed yesterday from apple's site as well lol.

https://www.reddit.com/r/HomeKit/comments/8zpsl4/apple_has_taken_down_all_listings_of_doorbells/

**Comment by DanielWeeber** [comment]
I read that also, but only for US site. Lets see whats coming :)
