### ISSUE TITLE
Speaker Not supported?

### ISSUE THREAD

**Issue by sulph68** [Supereg/homebridge-http-speaker#4]
hi

Thanks for this plugin! Its exactly what I was looking for!
I wrote a set of APIs to have the speaker plugin communicate with my Volumio Setup. But while the homebridge logs sees the http-speakers, the Home App shows the speaker as unsupported.
my iOS device is on iOS 12.

May I know what might be the issue?

Thanks lots

**Comment by Supereg** [comment]
I may redirect you to the „Compatibility notice“ of the README file [here](https://github.com/Supereg/homebridge-http-speaker/blob/master/README.md/#compatibility-notice).

The speaker service is only designed to be a sub service of the doorbell service.

Best regards
Andi
